import { Metadata } from "next";
import HeroUIWrapper from "@/providers/HeroUIWrapper";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NextTopLoader easing="ease" showSpinner={false} />
        <HeroUIWrapper>{children}</HeroUIWrapper>
      </body>
    </html>
  );
}
