name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5
            
            - name: Install Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            
            - name: Install dependencies
              run: bun install

            - name: Run lint
              run: bun run lint

            - name: Run build
              run: bun run build